# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Node.js dependencies (npm)
  - package-ecosystem: "npm" # Use "npm" for Node.js projects
    directory: "/" # Location of package.json (root directory)
    schedule:
      interval: "daily" # Check for updates every day
      time: "04:00" # Run at 4 AM UK time (BST)
      timezone: "Europe/London" # Timezone for scheduling updates (UK)
    allow:
      - dependency-type: "all" # Allow updates to all types of dependencies (prod and dev)
      
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory for GitHub Actions workflows
    schedule:
      interval: "weekly" # Check for updates every week
      day: "monday" # Run on Mondays
      time: "04:00" # Run at 4 AM UK time (BST)
      timezone: "Europe/London" # Timezone for scheduling updates (UK)
